/**
 * Auto-generated license information
 * Generated on: 2026-01-18T16:28:36.296Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate-licenses
 *
 * This file contains:
 * - Direct npm dependencies (excluding build/dev tools)
 * - Google Fonts used in the project
 */

export interface LicenseInfo {
  name: string;
  author: string;
  license: string;
  link: string;
  category: 'npm' | 'font' | 'manual';
}

export const NPM_LICENSES: LicenseInfo[] = [
  {
    "name": "@daun_jung/korean-romanizer",
    "author": "Daunjung-dev",
    "license": "MIT",
    "link": "https://github.com/daunjung-dev/korean-romanizer",
    "category": "npm"
  },
  {
    "name": "@dehoist/romanize-thai",
    "author": "Unknown",
    "license": "MPL-2.0",
    "link": "https://github.com/Dehoist/Open-Source",
    "category": "npm"
  },
  {
    "name": "@indic-transliteration/sanscript",
    "author": "Arun Prasad and Sanskrit coders",
    "license": "MIT",
    "link": "https://github.com/indic-transliteration/sanscript.js",
    "category": "npm"
  },
  {
    "name": "@mui/material",
    "author": "MUI Team",
    "license": "MIT",
    "link": "https://github.com/mui/material-ui",
    "category": "npm"
  },
  {
    "name": "@mui/material",
    "author": "MUI Team",
    "license": "MIT",
    "link": "https://github.com/mui/material-ui",
    "category": "npm"
  },
  {
    "name": "@web-lite/scroll-picker",
    "author": "mohammadhossein",
    "license": "MIT",
    "link": "https://github.com/weblite-im/scroll-picker",
    "category": "npm"
  },
  {
    "name": "arabic-transliterate",
    "author": "Vyshantha Simha",
    "license": "ISC",
    "link": "https://github.com/Vyshantha/arabic-transliterate",
    "category": "npm"
  },
  {
    "name": "axios",
    "author": "Matt Zabriskie",
    "license": "MIT",
    "link": "https://github.com/axios/axios",
    "category": "npm"
  },
  {
    "name": "get-artist-title",
    "author": "Renée Kooi",
    "license": "MIT",
    "link": "https://github.com/goto-bus-stop/get-artist-title",
    "category": "npm"
  },
  {
    "name": "gsap",
    "author": "Unknown",
    "license": "Custom: https://gsap.com/GSAP-share-image.png",
    "link": "https://github.com/greensock/GSAP",
    "category": "npm"
  },
  {
    "name": "i18next-browser-languagedetector",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/i18next-browser-languageDetector",
    "category": "npm"
  },
  {
    "name": "i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/i18next",
    "category": "npm"
  },
  {
    "name": "i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/i18next",
    "category": "npm"
  },
  {
    "name": "kuroshiro-analyzer-kuromoji",
    "author": "Hexen Qi",
    "license": "MIT",
    "link": "https://github.com/hexenq/kuroshiro-analyzer-kuromoji",
    "category": "npm"
  },
  {
    "name": "kuroshiro",
    "author": "Hexen Qi",
    "license": "MIT",
    "link": "https://github.com/hexenq/kuroshiro",
    "category": "npm"
  },
  {
    "name": "matter-js",
    "author": "Liam Brummitt",
    "license": "MIT",
    "link": "https://github.com/liabru/matter-js",
    "category": "npm"
  },
  {
    "name": "motion",
    "author": "Matt Perry",
    "license": "MIT",
    "link": "https://github.com/motiondivision/motion",
    "category": "npm"
  },
  {
    "name": "normalize.css",
    "author": "Unknown",
    "license": "MIT",
    "link": "https://github.com/necolas/normalize.css",
    "category": "npm"
  },
  {
    "name": "path-browserify",
    "author": "James Halliday",
    "license": "MIT",
    "link": "https://github.com/browserify/path-browserify",
    "category": "npm"
  },
  {
    "name": "pinyin-pro",
    "author": "zh-lx",
    "license": "MIT",
    "link": "https://github.com/zh-lx/pinyin-pro",
    "category": "npm"
  },
  {
    "name": "react-dom",
    "author": "Unknown",
    "license": "MIT",
    "link": "https://github.com/facebook/react",
    "category": "npm"
  },
  {
    "name": "react-error-boundary",
    "author": "Brian Vaughn",
    "license": "MIT",
    "link": "https://github.com/bvaughn/react-error-boundary",
    "category": "npm"
  },
  {
    "name": "react-i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/react-i18next",
    "category": "npm"
  },
  {
    "name": "react-i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/react-i18next",
    "category": "npm"
  },
  {
    "name": "react-icons",
    "author": "Goran Gajic",
    "license": "MIT",
    "link": "https://github.com/react-icons/react-icons",
    "category": "npm"
  },
  {
    "name": "react-tooltip",
    "author": "ReactTooltip",
    "license": "MIT",
    "link": "https://github.com/ReactTooltip/react-tooltip",
    "category": "npm"
  },
  {
    "name": "react",
    "author": "Unknown",
    "license": "MIT",
    "link": "https://github.com/facebook/react",
    "category": "npm"
  },
  {
    "name": "styled-normalize",
    "author": "Sergey Sova",
    "license": "MIT",
    "link": "https://github.com/sergeysova/styled-normalize",
    "category": "npm"
  }
];

export const FONT_LICENSES: LicenseInfo[] = [
  {
    "name": "Noto Sans KR",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+KR/license",
    "category": "font"
  },
  {
    "name": "Monoton",
    "author": "Vernon Adams",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Monoton/license",
    "category": "font"
  },
  {
    "name": "Dancing Script",
    "author": "Impallari Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Dancing+Script/license",
    "category": "font"
  },
  {
    "name": "Shadows Into Light",
    "author": "Kimberly Geswein",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Shadows+Into+Light/license",
    "category": "font"
  },
  {
    "name": "Jolly Lodger",
    "author": "Neapolitan, Brian J. Bonislawsky",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Jolly+Lodger/license",
    "category": "font"
  },
  {
    "name": "Creepster",
    "author": "Font Diner",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Creepster/license",
    "category": "font"
  },
  {
    "name": "Snowburst One",
    "author": "Sorkin Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Snowburst+One/license",
    "category": "font"
  },
  {
    "name": "Baloo Paaji 2",
    "author": "Ek Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Baloo+Paaji+2/license",
    "category": "font"
  },
  {
    "name": "Pacifico",
    "author": "Vernon Adams, Jacques Le Bailly, Botjo Nikoltchev, Ani Petrova",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Pacifico/license",
    "category": "font"
  },
  {
    "name": "Lobster",
    "author": "Impallari Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Lobster/license",
    "category": "font"
  },
  {
    "name": "Bebas Neue",
    "author": "Ryoichi Tsunekawa",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Bebas+Neue/license",
    "category": "font"
  },
  {
    "name": "Noto Sans JP",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+JP/license",
    "category": "font"
  },
  {
    "name": "Noto Serif JP",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Serif+JP/license",
    "category": "font"
  },
  {
    "name": "Dela Gothic One",
    "author": "Syotaro Hayashi, Ikkou, Yugo Eguchi, Raku Inagaki",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Dela+Gothic+One/license",
    "category": "font"
  },
  {
    "name": "Kaisei Decol",
    "author": "Type Project, Yuki Miyazawa, Ayano Ito",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Kaisei+Decol/license",
    "category": "font"
  },
  {
    "name": "Hachi Maru Pop",
    "author": "Noriko Takao, Fontworks Inc.",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Hachi+Maru+Pop/license",
    "category": "font"
  },
  {
    "name": "Potta One",
    "author": "Phawin Khwanmuang",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Potta+One/license",
    "category": "font"
  },
  {
    "name": "RocknRoll One",
    "author": "Fontworks Inc., Kazunori Yamagata, Shinji Sato",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/RocknRoll+One/license",
    "category": "font"
  },
  {
    "name": "Noto Sans SC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+SC/license",
    "category": "font"
  },
  {
    "name": "Noto Serif SC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Serif+SC/license",
    "category": "font"
  },
  {
    "name": "Noto Sans TC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+TC/license",
    "category": "font"
  },
  {
    "name": "Noto Serif TC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Serif+TC/license",
    "category": "font"
  },
  {
    "name": "Ma Shan Zheng",
    "author": "Liu Zhao",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Ma+Shan+Zheng/license",
    "category": "font"
  },
  {
    "name": "Zcool XiaoWei",
    "author": "ZCOOL, Liu Wei",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Zcool+XiaoWei/license",
    "category": "font"
  },
  {
    "name": "Long Cang",
    "author": "Liu Xiu",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Long+Cang/license",
    "category": "font"
  },
  {
    "name": "LXGW WenKai Mono TC",
    "author": "LXGW",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/LXGW+WenKai+Mono+TC/license",
    "category": "font"
  },
  {
    "name": "Noto Sans Mono",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+Mono/license",
    "category": "font"
  },
  {
    "name": "Roboto Mono",
    "author": "Christian Robertson",
    "license": "Apache License, Version 2.0",
    "link": "https://fonts.google.com/specimen/Roboto+Mono/license",
    "category": "font"
  },
  {
    "name": "JetBrains Mono",
    "author": "JetBrains",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/JetBrains+Mono/license",
    "category": "font"
  },
  {
    "name": "Source Code Pro",
    "author": "Paul D. Hunt",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Source+Code+Pro/license",
    "category": "font"
  }
];

export const ALL_LICENSES: LicenseInfo[] = [
  {
    "name": "@daun_jung/korean-romanizer",
    "author": "Daunjung-dev",
    "license": "MIT",
    "link": "https://github.com/daunjung-dev/korean-romanizer",
    "category": "npm"
  },
  {
    "name": "@dehoist/romanize-thai",
    "author": "Unknown",
    "license": "MPL-2.0",
    "link": "https://github.com/Dehoist/Open-Source",
    "category": "npm"
  },
  {
    "name": "@indic-transliteration/sanscript",
    "author": "Arun Prasad and Sanskrit coders",
    "license": "MIT",
    "link": "https://github.com/indic-transliteration/sanscript.js",
    "category": "npm"
  },
  {
    "name": "@mui/material",
    "author": "MUI Team",
    "license": "MIT",
    "link": "https://github.com/mui/material-ui",
    "category": "npm"
  },
  {
    "name": "@mui/material",
    "author": "MUI Team",
    "license": "MIT",
    "link": "https://github.com/mui/material-ui",
    "category": "npm"
  },
  {
    "name": "@web-lite/scroll-picker",
    "author": "mohammadhossein",
    "license": "MIT",
    "link": "https://github.com/weblite-im/scroll-picker",
    "category": "npm"
  },
  {
    "name": "arabic-transliterate",
    "author": "Vyshantha Simha",
    "license": "ISC",
    "link": "https://github.com/Vyshantha/arabic-transliterate",
    "category": "npm"
  },
  {
    "name": "axios",
    "author": "Matt Zabriskie",
    "license": "MIT",
    "link": "https://github.com/axios/axios",
    "category": "npm"
  },
  {
    "name": "get-artist-title",
    "author": "Renée Kooi",
    "license": "MIT",
    "link": "https://github.com/goto-bus-stop/get-artist-title",
    "category": "npm"
  },
  {
    "name": "gsap",
    "author": "Unknown",
    "license": "Custom: https://gsap.com/GSAP-share-image.png",
    "link": "https://github.com/greensock/GSAP",
    "category": "npm"
  },
  {
    "name": "i18next-browser-languagedetector",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/i18next-browser-languageDetector",
    "category": "npm"
  },
  {
    "name": "i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/i18next",
    "category": "npm"
  },
  {
    "name": "i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/i18next",
    "category": "npm"
  },
  {
    "name": "kuroshiro-analyzer-kuromoji",
    "author": "Hexen Qi",
    "license": "MIT",
    "link": "https://github.com/hexenq/kuroshiro-analyzer-kuromoji",
    "category": "npm"
  },
  {
    "name": "kuroshiro",
    "author": "Hexen Qi",
    "license": "MIT",
    "link": "https://github.com/hexenq/kuroshiro",
    "category": "npm"
  },
  {
    "name": "matter-js",
    "author": "Liam Brummitt",
    "license": "MIT",
    "link": "https://github.com/liabru/matter-js",
    "category": "npm"
  },
  {
    "name": "motion",
    "author": "Matt Perry",
    "license": "MIT",
    "link": "https://github.com/motiondivision/motion",
    "category": "npm"
  },
  {
    "name": "normalize.css",
    "author": "Unknown",
    "license": "MIT",
    "link": "https://github.com/necolas/normalize.css",
    "category": "npm"
  },
  {
    "name": "path-browserify",
    "author": "James Halliday",
    "license": "MIT",
    "link": "https://github.com/browserify/path-browserify",
    "category": "npm"
  },
  {
    "name": "pinyin-pro",
    "author": "zh-lx",
    "license": "MIT",
    "link": "https://github.com/zh-lx/pinyin-pro",
    "category": "npm"
  },
  {
    "name": "react-dom",
    "author": "Unknown",
    "license": "MIT",
    "link": "https://github.com/facebook/react",
    "category": "npm"
  },
  {
    "name": "react-error-boundary",
    "author": "Brian Vaughn",
    "license": "MIT",
    "link": "https://github.com/bvaughn/react-error-boundary",
    "category": "npm"
  },
  {
    "name": "react-i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/react-i18next",
    "category": "npm"
  },
  {
    "name": "react-i18next",
    "author": "Jan Mühlemann",
    "license": "MIT",
    "link": "https://github.com/i18next/react-i18next",
    "category": "npm"
  },
  {
    "name": "react-icons",
    "author": "Goran Gajic",
    "license": "MIT",
    "link": "https://github.com/react-icons/react-icons",
    "category": "npm"
  },
  {
    "name": "react-tooltip",
    "author": "ReactTooltip",
    "license": "MIT",
    "link": "https://github.com/ReactTooltip/react-tooltip",
    "category": "npm"
  },
  {
    "name": "react",
    "author": "Unknown",
    "license": "MIT",
    "link": "https://github.com/facebook/react",
    "category": "npm"
  },
  {
    "name": "styled-normalize",
    "author": "Sergey Sova",
    "license": "MIT",
    "link": "https://github.com/sergeysova/styled-normalize",
    "category": "npm"
  },
  {
    "name": "Noto Sans KR",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+KR/license",
    "category": "font"
  },
  {
    "name": "Monoton",
    "author": "Vernon Adams",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Monoton/license",
    "category": "font"
  },
  {
    "name": "Dancing Script",
    "author": "Impallari Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Dancing+Script/license",
    "category": "font"
  },
  {
    "name": "Shadows Into Light",
    "author": "Kimberly Geswein",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Shadows+Into+Light/license",
    "category": "font"
  },
  {
    "name": "Jolly Lodger",
    "author": "Neapolitan, Brian J. Bonislawsky",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Jolly+Lodger/license",
    "category": "font"
  },
  {
    "name": "Creepster",
    "author": "Font Diner",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Creepster/license",
    "category": "font"
  },
  {
    "name": "Snowburst One",
    "author": "Sorkin Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Snowburst+One/license",
    "category": "font"
  },
  {
    "name": "Baloo Paaji 2",
    "author": "Ek Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Baloo+Paaji+2/license",
    "category": "font"
  },
  {
    "name": "Pacifico",
    "author": "Vernon Adams, Jacques Le Bailly, Botjo Nikoltchev, Ani Petrova",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Pacifico/license",
    "category": "font"
  },
  {
    "name": "Lobster",
    "author": "Impallari Type",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Lobster/license",
    "category": "font"
  },
  {
    "name": "Bebas Neue",
    "author": "Ryoichi Tsunekawa",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Bebas+Neue/license",
    "category": "font"
  },
  {
    "name": "Noto Sans JP",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+JP/license",
    "category": "font"
  },
  {
    "name": "Noto Serif JP",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Serif+JP/license",
    "category": "font"
  },
  {
    "name": "Dela Gothic One",
    "author": "Syotaro Hayashi, Ikkou, Yugo Eguchi, Raku Inagaki",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Dela+Gothic+One/license",
    "category": "font"
  },
  {
    "name": "Kaisei Decol",
    "author": "Type Project, Yuki Miyazawa, Ayano Ito",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Kaisei+Decol/license",
    "category": "font"
  },
  {
    "name": "Hachi Maru Pop",
    "author": "Noriko Takao, Fontworks Inc.",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Hachi+Maru+Pop/license",
    "category": "font"
  },
  {
    "name": "Potta One",
    "author": "Phawin Khwanmuang",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Potta+One/license",
    "category": "font"
  },
  {
    "name": "RocknRoll One",
    "author": "Fontworks Inc., Kazunori Yamagata, Shinji Sato",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/RocknRoll+One/license",
    "category": "font"
  },
  {
    "name": "Noto Sans SC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+SC/license",
    "category": "font"
  },
  {
    "name": "Noto Serif SC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Serif+SC/license",
    "category": "font"
  },
  {
    "name": "Noto Sans TC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+TC/license",
    "category": "font"
  },
  {
    "name": "Noto Serif TC",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Serif+TC/license",
    "category": "font"
  },
  {
    "name": "Ma Shan Zheng",
    "author": "Liu Zhao",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Ma+Shan+Zheng/license",
    "category": "font"
  },
  {
    "name": "Zcool XiaoWei",
    "author": "ZCOOL, Liu Wei",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Zcool+XiaoWei/license",
    "category": "font"
  },
  {
    "name": "Long Cang",
    "author": "Liu Xiu",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Long+Cang/license",
    "category": "font"
  },
  {
    "name": "LXGW WenKai Mono TC",
    "author": "LXGW",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/LXGW+WenKai+Mono+TC/license",
    "category": "font"
  },
  {
    "name": "Noto Sans Mono",
    "author": "Google",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Noto+Sans+Mono/license",
    "category": "font"
  },
  {
    "name": "Roboto Mono",
    "author": "Christian Robertson",
    "license": "Apache License, Version 2.0",
    "link": "https://fonts.google.com/specimen/Roboto+Mono/license",
    "category": "font"
  },
  {
    "name": "JetBrains Mono",
    "author": "JetBrains",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/JetBrains+Mono/license",
    "category": "font"
  },
  {
    "name": "Source Code Pro",
    "author": "Paul D. Hunt",
    "license": "SIL Open Font License, Version 1.1",
    "link": "https://fonts.google.com/specimen/Source+Code+Pro/license",
    "category": "font"
  }
];
