/**
 * Auto-generated license information
 * Generated on: 2026-02-20T12:33:48.989Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate-licenses
 *
 * This file contains:
 * - Direct npm dependencies (excluding build/dev tools)
 * - Google Fonts used in the project
 */

export interface LicenseInfo {
  name: string;
  author: string;
  license: string;
  link: string;
  category: 'npm' | 'font' | 'manual';
}

export const NPM_LICENSES: LicenseInfo[] = [
  {
    name: '@daun_jung/korean-romanizer',
    author: 'Daunjung-dev',
    license: 'MIT',
    link: 'https://github.com/daunjung-dev/korean-romanizer',
    category: 'npm',
  },
  {
    name: '@dehoist/romanize-thai',
    author: 'Unknown',
    license: 'MPL-2.0',
    link: 'https://github.com/Dehoist/Open-Source',
    category: 'npm',
  },
  {
    name: '@indic-transliteration/sanscript',
    author: 'Arun Prasad and Sanskrit coders',
    license: 'MIT',
    link: 'https://github.com/indic-transliteration/sanscript.js',
    category: 'npm',
  },
  {
    name: 'arabic-transliterate',
    author: 'Vyshantha Simha',
    license: 'ISC',
    link: 'https://github.com/Vyshantha/arabic-transliterate',
    category: 'npm',
  },
  {
    name: 'i18next-browser-languagedetector',
    author: 'Jan Mühlemann',
    license: 'MIT',
    link: 'https://github.com/i18next/i18next-browser-languageDetector',
    category: 'npm',
  },
  {
    name: 'i18next',
    author: 'Jan Mühlemann',
    license: 'MIT',
    link: 'https://github.com/i18next/i18next',
    category: 'npm',
  },
  {
    name: 'kuroshiro-analyzer-kuromoji',
    author: 'Hexen Qi',
    license: 'MIT',
    link: 'https://github.com/hexenq/kuroshiro-analyzer-kuromoji',
    category: 'npm',
  },
  {
    name: 'kuroshiro',
    author: 'Hexen Qi',
    license: 'MIT',
    link: 'https://github.com/hexenq/kuroshiro',
    category: 'npm',
  },
  {
    name: 'normalize.css',
    author: 'Unknown',
    license: 'MIT',
    link: 'https://github.com/necolas/normalize.css',
    category: 'npm',
  },
  {
    name: 'path-browserify',
    author: 'James Halliday',
    license: 'MIT',
    link: 'https://github.com/browserify/path-browserify',
    category: 'npm',
  },
  {
    name: 'pinyin-pro',
    author: 'zh-lx',
    license: 'MIT',
    link: 'https://github.com/zh-lx/pinyin-pro',
    category: 'npm',
  },
  {
    name: 'react-dom',
    author: 'Unknown',
    license: 'MIT',
    link: 'https://github.com/facebook/react',
    category: 'npm',
  },
  {
    name: 'react-error-boundary',
    author: 'Brian Vaughn',
    license: 'MIT',
    link: 'https://github.com/bvaughn/react-error-boundary',
    category: 'npm',
  },
  {
    name: 'react-i18next',
    author: 'Jan Mühlemann',
    license: 'MIT',
    link: 'https://github.com/i18next/react-i18next',
    category: 'npm',
  },
  {
    name: 'react-icons',
    author: 'Goran Gajic',
    license: 'MIT',
    link: 'https://github.com/react-icons/react-icons',
    category: 'npm',
  },
  {
    name: 'react',
    author: 'Unknown',
    license: 'MIT',
    link: 'https://github.com/facebook/react',
    category: 'npm',
  },
  {
    name: 'styled-components',
    author: 'Glen Maddern',
    license: 'MIT',
    link: 'https://github.com/styled-components/styled-components',
    category: 'npm',
  },
  {
    name: 'styled-normalize',
    author: 'Sergey Sova',
    license: 'MIT',
    link: 'https://github.com/sergeysova/styled-normalize',
    category: 'npm',
  },
];

export const FONT_LICENSES: LicenseInfo[] = [];

export const ALL_LICENSES: LicenseInfo[] = [
  {
    name: '@daun_jung/korean-romanizer',
    author: 'Daunjung-dev',
    license: 'MIT',
    link: 'https://github.com/daunjung-dev/korean-romanizer',
    category: 'npm',
  },
  {
    name: '@dehoist/romanize-thai',
    author: 'Unknown',
    license: 'MPL-2.0',
    link: 'https://github.com/Dehoist/Open-Source',
    category: 'npm',
  },
  {
    name: '@indic-transliteration/sanscript',
    author: 'Arun Prasad and Sanskrit coders',
    license: 'MIT',
    link: 'https://github.com/indic-transliteration/sanscript.js',
    category: 'npm',
  },
  {
    name: 'arabic-transliterate',
    author: 'Vyshantha Simha',
    license: 'ISC',
    link: 'https://github.com/Vyshantha/arabic-transliterate',
    category: 'npm',
  },
  {
    name: 'i18next-browser-languagedetector',
    author: 'Jan Mühlemann',
    license: 'MIT',
    link: 'https://github.com/i18next/i18next-browser-languageDetector',
    category: 'npm',
  },
  {
    name: 'i18next',
    author: 'Jan Mühlemann',
    license: 'MIT',
    link: 'https://github.com/i18next/i18next',
    category: 'npm',
  },
  {
    name: 'kuroshiro-analyzer-kuromoji',
    author: 'Hexen Qi',
    license: 'MIT',
    link: 'https://github.com/hexenq/kuroshiro-analyzer-kuromoji',
    category: 'npm',
  },
  {
    name: 'kuroshiro',
    author: 'Hexen Qi',
    license: 'MIT',
    link: 'https://github.com/hexenq/kuroshiro',
    category: 'npm',
  },
  {
    name: 'normalize.css',
    author: 'Unknown',
    license: 'MIT',
    link: 'https://github.com/necolas/normalize.css',
    category: 'npm',
  },
  {
    name: 'path-browserify',
    author: 'James Halliday',
    license: 'MIT',
    link: 'https://github.com/browserify/path-browserify',
    category: 'npm',
  },
  {
    name: 'pinyin-pro',
    author: 'zh-lx',
    license: 'MIT',
    link: 'https://github.com/zh-lx/pinyin-pro',
    category: 'npm',
  },
  {
    name: 'react-dom',
    author: 'Unknown',
    license: 'MIT',
    link: 'https://github.com/facebook/react',
    category: 'npm',
  },
  {
    name: 'react-error-boundary',
    author: 'Brian Vaughn',
    license: 'MIT',
    link: 'https://github.com/bvaughn/react-error-boundary',
    category: 'npm',
  },
  {
    name: 'react-i18next',
    author: 'Jan Mühlemann',
    license: 'MIT',
    link: 'https://github.com/i18next/react-i18next',
    category: 'npm',
  },
  {
    name: 'react-icons',
    author: 'Goran Gajic',
    license: 'MIT',
    link: 'https://github.com/react-icons/react-icons',
    category: 'npm',
  },
  {
    name: 'react',
    author: 'Unknown',
    license: 'MIT',
    link: 'https://github.com/facebook/react',
    category: 'npm',
  },
  {
    name: 'styled-components',
    author: 'Glen Maddern',
    license: 'MIT',
    link: 'https://github.com/styled-components/styled-components',
    category: 'npm',
  },
  {
    name: 'styled-normalize',
    author: 'Sergey Sova',
    license: 'MIT',
    link: 'https://github.com/sergeysova/styled-normalize',
    category: 'npm',
  },
];
