export const STORAGE_KEYS = {
  CONTENT_ENABLED: 'contentEnabled',
  LANGUAGE: 'language',
  LAST_VIDEO_ID: 'lastVideoId',
  PREFERRED_ROMANIZATION_LANGUAGES: 'preferredRomanizationLanguages',
  HAS_COMPLETED_LANGUAGE_ONBOARDING: 'hasCompletedLanguageOnboarding',
  LOADED_ROMANIZER_LIBRARIES: 'loadedRomanizerLibraries',
  ACAPELLA_LEGAL_AGREEMENT_ACCEPTED: 'acapellaLegalAgreementAccepted',
  ACAPELLA_RECORDINGS_LIST: 'acapellaRecordingsList',
  HAS_COMPLETED_WELCOME: 'hasCompletedWelcome',
  TUTORIAL_STEP1_COMPLETED: 'tutorialStep1Completed',
  TUTORIAL_STEP2_COMPLETED: 'tutorialStep2Completed',
  TUTORIAL_SYNC_COMPLETED: 'tutorial_sync_completed',
  TUTORIAL_LOOP_COMPLETED: 'tutorial_loop_completed',
  TUTORIAL_CUSTOM_LYRICS_COMPLETED: 'tutorial_custom_lyrics_completed',
  TUTORIAL_SIDEBAR_COMPLETED: 'tutorial_sidebar_completed',
  TUTORIAL_JUMP_COMPLETED: 'tutorial_jump_completed',
  TUTORIAL_LYRICS_COMPLETED: 'tutorial_lyrics_completed',
  TUTORIAL_SEARCH_COMPLETED: 'tutorial_search_completed',
  TUTORIAL_RECORDING_COMPLETED: 'tutorial_recording_completed',
  TUTORIAL_TUNE_COMPLETED: 'tutorial_tune_completed',
  TUTORIAL_SETTINGS_COMPLETED: 'tutorial_settings_completed',
  SYNC_TOAST_DISMISSED_PREFIX: 'syncToastDismissed_',
} as const;
